/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [EntityKey]
      ,[EntityLabel]
      ,[ParentEntityKey]
      ,[ParentEntityLabel]
      ,[EntityName]
      ,[EntityDescription]
      ,[EntityType]
      ,[StartDate]
      ,[EndDate]
      ,[Status]
      ,[ETLLoadID]
      ,[LoadDate]
      ,[UpdateDate]
  FROM [ContosoRetailDW].[dbo].[DimEntity]